<?php

class Users extends FwModel {
    public static $ACL=array(
                        'ADMIN' => 100,
                        'MODER' => 80,
                        'USER'  => 0,
                    );
    public static $PERM_COOKIE_NAME='perm';
    public static $PERM_COOKIE_DAYS=356;
    public static $order_by = 'fname, lname';

    public $table_menu_items = 'menu_items';

    /** @return Users */
    public static function i() {
        return parent::i();
    }

    public function __construct() {
        parent::__construct();

        $this->table_name = 'users';
        $this->csv_export_fields = "id|id fname|First&nbsp;Name lname|Last&nbsp;Name email|Email add_time|Registered";
    }

    public function oneByEmail($email) {
        return $this->db->row($this->table_name, array("email" => $email));
    }

    public function getFullName($id) {
        $result='';
        $item = $this->one($id);
        if ($item['id']){
            $result=$item['fname'].' '.$item['lname'];
        }
        return $result;
    }

    #return standard list of id,iname where status=0 order by iname
    public function ilist($min_acl=null) {
        $where='';
        if (!is_null($min_acl)) $where=' and access_level>='.dbqi($min_acl);
        $sql  = "SELECT *, (fname+' '+lname) as iname FROM $this->table_name WHERE status=0 $where ORDER BY fname,lname";
        return $this->db->arr($sql);
    }

    public function getMultiList($hsel_ids, $min_acl=null){
        $rows = $this->ilist($min_acl);
        if (is_array($hsel_ids) && count($hsel_ids)){
            foreach ($rows as $k => $row) {
                $rows[$k]['is_checked'] = array_key_exists($row['id'], $hsel_ids)!==FALSE;
            }
        }

        return $rows;
    }

    public function add($item) {
        if (!array_key_exists('pwd', $item)) $item['pwd']=Utils::getRandStr(8); #generate password
        $item['pwd']=$this->hashPwd($item['pwd']);
        $id=parent::add($item);
        return $id;
    }

    public function update($id, $item){
        if (array_key_exists('pwd', $item)) $item['pwd']=$this->hashPwd($item['pwd']);
        return parent::update($id, $item);
    }

    public function isExists($email, $not_id=NULL) {
        return $this->isExistsByField($email, 'email', $not_id);
    }

    /**
     * generate password hash from plain password
     * @param  string $plain_pwd plain pwd
     * @return string            hash
     */
    public function hashPwd($plain_pwd){
        return password_hash($plain_pwd, PASSWORD_DEFAULT);
    }

    /**
     * return true if plain password has the same hash as provided
     * @param  string $plain_pwd plain pwd
     * @param  string $pwd_hash  password hash previously generated by hashPwd
     * @return bool            true or false
     */
    public function checkPwd($plain_pwd, $pwd_hash){
        return password_verify($plain_pwd, $pwd_hash);
    }

    public function doLogin($id) {
        $is_just_registered=$_SESSION['is_just_registered']+0;

        @session_destroy();
        session_start();
        $_SESSION['is_logged']=true;
        $_SESSION['XSS']=Utils::getRandStr(16);  #setup XSS code

        #fill up session data
        $this->reloadSession($id);
        $_SESSION['just_logged']=1;
        $_SESSION['is_just_registered']=$is_just_registered;
        session_write_close();

        $this->fw->model('FwEvents')->log('login', $id);

        //set permanent login if requested
        //if ($_REQUEST['is_remember']) createPermCookie($id);
        $this->createPermCookie($id);  #in this project no need is_remember

        $this->updateAfterLogin($id);
    }

    public function reloadSession($id=0){
        if (!$id) $id=Utils::me();
        $hU=$this->one($id);

        $_SESSION['user_id']=$id;
        $_SESSION['login']=$hU['email'];
        $_SESSION['lang']=$hU['lang'];

        $fname = trim($hU['fname']);
        $lname = trim($hU['lname']);
        $_SESSION['user_name']=$fname.($fname?' ':'').$lname; #will be empty if no user name set
        $_SESSION['access_level']=$hU['access_level'];
    }

    private function updateAfterLogin($id) {
        #update login vars
        $ip=getenv("REMOTE_ADDR");

        $host=gethostbyaddr($ip);

        $vars=array(
            'login_time'    => '~!now()',
            'login_ip'      => $ip,
            'login_host'    => $host,
        );
        $this->update($id, $vars);
    }

    public function createPermCookie($id){
        $root_domain0=$this->fw->config->ROOT_DOMAIN0;

        $cookie_id=substr(Utils::getRandStr(16).time(),0,32);

        $vars=array(
            'cookie_id' => $cookie_id,
            'users_id'  => $id
        );
        $this->db->insert('user_cookie', $vars, array('replace' => 1));

        setcookie(self::$PERM_COOKIE_NAME, $cookie_id, time()+60*60*24*self::$PERM_COOKIE_DAYS, "/", (preg_match('/\./',$root_domain0))?'.'.$root_domain0:'');
        #rwe("[$root_domain0] ".self::$PERM_COOKIE_NAME.", $cookie_id, ".(time()+60*60*24*self::$PERM_COOKIE_DAYS));

        return $cookie_id;
    }

    # check for permanent login cookie and if it's present - doLogin
    public function checkPermanentLogin(){
        $root_domain0=$this->fw->config->ROOT_DOMAIN0;

        $result = false;

        $cookie_id=@$_COOKIE[ self::$PERM_COOKIE_NAME ];
        #rw("cookies:");
        #print_r($_COOKIE);
        #exit;

        if ($cookie_id) {
            $u_id=$this->db->value("SELECT users_id
                  FROM user_cookie
                 WHERE cookie_id=".$this->db->quote($cookie_id)."
                   and add_time>=FROM_DAYS(TO_DAYS(now())-".self::$PERM_COOKIE_DAYS.")
            ");

            if ($u_id>0){
                $result=true;
                #logger("PERMANENT LOGIN");
                $this->doLogin($u_id);
            }else{
                #cookie is not found in DB - clean it (so it will not put load on DB during next pages)
                setcookie(self::$PERM_COOKIE_NAME, FALSE, -1, "/", (preg_match('/\./',$root_domain0))?'.'.$root_domain0:'' );
            }
        }
        return $result;
    }

    public function removePermCookie(){
        $cookie_id=$_COOKIE[ self::$PERM_COOKIE_NAME ];

        setcookie(self::$PERM_COOKIE_NAME, FALSE, -1, "/");

        #cleanup in DB (user's cookie and ALL old cookies)
        $this->db->query("DELETE FROM user_cookie
            WHERE cookie_id=".$this->db->quote($cookie_id)."
               or add_time<FROM_DAYS(TO_DAYS(now())-".self::$PERM_COOKIE_DAYS.")
        ");

    }

    public function isAccess($access_str) {
        $req_level=self::$ACL[$access_str]+0;

        return $_SESSION['access_level']>=$req_level ? true : false;
    }

    /**
     * return sql for limiting access according to current user ACL
     * @param  string $alias optional, add_users_id field alias with dot. Example: 'c.'. If not provided - no alias used
     * @param  string $field optional, add_users_id field name
     * @return string        sql query string like " and add_users_id=".Utils::me()
     */
    public function sql_acl($alias='', $field=''){
        $result='';
        if (self::isAccess('MODER')){
            //if we are admin user - allow access to all records
        }else{
            //if we are normal user - allows access only records we created
            if (!$field) $field = 'add_users_id';

            $result=' and '.$alias.$field.'='.dbqi(Utils::me()).' ';
        }
        return $result;
    }

    public function loadMenuItems(){
        if (!isset($_SESSION['menu_items'])) {
            $_SESSION['menu_items']=$this->db->arr("select * from $this->table_menu_items where status=0 and access_level<=".dbqi($_SESSION['access_level'])." order by iname");
        }
        $this->fw->GLOBAL['menu_items'] = $_SESSION['menu_items'];
    }
}

?>
